# Generated by Django 6.0.2 on 2026-02-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='Subject_name',
        ),
    ]
