# Generated by Django 6.0.2 on 2026-02-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_name_subject_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus_image',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
